- name: copying the service file and starting the service file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: ENABLEING AND RESTARTING the  server
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes

